#!/bin/sh
set -e
chown root:root /usr/bin/lite-tweaks
chown root:root /usr/bin/lite-tweaks-super
chown root:root /usr/share/applications/litecleaner.desktop
chown root:root /usr/share/pixmaps/litetweaks.png
