#!/bin/sh
set -e
chown root:root /usr/bin/lite-tweaks
chown root:root /usr/bin/lite-tweaks-super
chown root:root /usr/share/applications/litecleaner.desktop
chown root:root /usr/share/pixmaps/litetweaks.png
chown root:root /usr/share/liteappsicons/litetweaks -R
chown root:root /usr/local/sbin -R
chmod 755 /usr/local/sbin/dryapt

# Folders and files permissions
find /usr/share/liteappsicons/ -type d -exec chmod 755 {} \;
find /usr/share/liteappsicons/ -type f -exec chmod 644 {} \;
